---
- name: install python3-libvirt
  dnf:
    state: present
    name: 'python3-libvirt'

- name: define VM
  virt:
    command: define
    xml: "{{ xml }}"

- name: start VM
  virt:
    name: "{{ domain }}"
    state: running

- name: wait for SSH
  wait_for: host={{ host }} port=22 search_regex=SSH state=present timeout=120
