---
- name: set operating system specific variables
  include_vars: "{{ lookup('first_found', filenames) }}"
  vars:
    filenames:
      files:
        - "{{ ansible_facts['distribution'] }}_{{ ansible_facts['distribution_version'] }}.yml"
        - "{{ ansible_facts['distribution'] }}_{{ ansible_facts['distribution_major_version'] }}.yml"
        - "{{ ansible_facts['distribution'] }}.yml"
        - "{{ ansible_facts['os_family'] }}.yml"
        - "default.yml"
      paths:
        - "{{ role_path }}/vars"

- name: install QEMU build dependencies
  dnf:
    state: present
    name: "{{ __qemu_builddep_packages }}"

- name: fetch sources from git
  git:
    depth: 1 # shallow clone
    dest: "{{ path | default('qemu') }}"
    repo: "{{ repo | default('https://gitlab.com/qemu-project/qemu.git') }}"
    version: "{{ version | default('master') }}"
    recursive: no

- name: build QEMU
  shell: "cd {{ path | default('qemu') }} && {{ configure_env_vars | default('') }} ./configure {{ configure_args | default('--target-list=x86_64-softmmu') }} && make -j$(nproc)"
